// Generated by CoffeeScript 1.9.2
var Hub, Publish, Receive, Shulz, async, cuid;

cuid = require('cuid');

async = require('odo-async');

Publish = require('./publish');

Receive = require('./receive');

Shulz = require('shulz');

Hub = require('odo-hub');

module.exports = function(options) {
  var _subscribe, _unsubscribe, advertise, bind, hub, publisher, receiver, send, subscriptions;
  advertise = options.advertise;
  if (advertise == null) {
    advertise = options.bind;
  }
  bind = options.bind;
  subscriptions = {};
  _subscribe = function(key, address) {
    if (subscriptions[key] == null) {
      subscriptions[key] = {};
    }
    subscriptions[key][address] = true;
    return publisher.register(address, address);
  };
  _unsubscribe = function(key, address) {
    if (subscriptions[key] == null) {
      return;
    }
    return delete subscriptions[key][address];
  };
  hub = Hub.create();
  hub.every('_subscribe', function(m, cb) {
    var i, key, len, ref;
    ref = m.keys;
    for (i = 0, len = ref.length; i < len; i++) {
      key = ref[i];
      _subscribe(key, m.address);
    }
    return cb();
  });
  hub.every('_unsubscribe', function(m, cb) {
    var i, key, len, ref;
    ref = m.keys;
    for (i = 0, len = ref.length; i < len; i++) {
      key = ref[i];
      _unsubscribe(key, m.address);
    }
    return cb();
  });
  publisher = Publish();
  receiver = Receive(bind, function(envelope, done) {
    var fn, i, key, len, ref, tasks;
    envelope = JSON.parse(envelope.toString());
    tasks = [];
    ref = envelope.keys;
    fn = function(key) {
      return tasks.push(function(cb) {
        return hub.emit(key, envelope.data, cb);
      });
    };
    for (i = 0, len = ref.length; i < len; i++) {
      key = ref[i];
      fn(key);
    }
    return async.parallel(tasks, done);
  });
  send = function(addresses, msgid, keys, data, cb) {
    var envelope, message;
    envelope = {
      id: msgid,
      keys: keys,
      sent: new Date(),
      data: data
    };
    message = JSON.stringify(envelope);
    return publisher.publish(msgid, message, addresses, cb);
  };
  return {
    publish: function(keys, data, cb) {
      var _, address, addresses, i, key, len, msgid, ref;
      if (!(keys instanceof Array)) {
        keys = [keys];
      }
      addresses = {};
      for (i = 0, len = keys.length; i < len; i++) {
        key = keys[i];
        if (subscriptions[key] == null) {
          continue;
        }
        ref = subscriptions[key];
        for (address in ref) {
          _ = ref[address];
          addresses[address] = true;
        }
      }
      addresses = Object.keys(addresses);
      msgid = cuid();
      if (addresses.length === 0) {
        if (cb != null) {
          async.delay(cb);
        }
        return msgid;
      }
      send(addresses, msgid, keys, data, function() {
        if (cb != null) {
          return async.delay(cb);
        }
      });
      return msgid;
    },
    subscribe: function(address, keys, cb) {
      var fn, i, key, len, subscribemsgids, tasks;
      if (!(keys instanceof Array)) {
        keys = [keys];
      }
      tasks = [];
      subscribemsgids = [];
      publisher.register(address, address);
      fn = function(key) {
        var data, msgid;
        msgid = cuid();
        subscribemsgids.push(msgid);
        data = {
          keys: keys,
          address: advertise
        };
        return tasks.push(function(cb) {
          return send(address, msgid, ['_subscribe'], data, cb);
        });
      };
      for (i = 0, len = keys.length; i < len; i++) {
        key = keys[i];
        fn(key);
      }
      async.parallel(tasks, function() {
        if (cb != null) {
          return async.delay(cb);
        }
      });
      return subscribemsgids;
    },
    unsubscribe: function(address, keys, cb) {
      var fn, i, key, len, tasks, unsubscribemsgids;
      if (!(keys instanceof Array)) {
        keys = [keys];
      }
      tasks = [];
      unsubscribemsgids = [];
      publisher.register(address, address);
      fn = function(key) {
        var envelope, message, msgid;
        msgid = cuid();
        unsubscribemsgids.push(msgid);
        envelope = {
          id: msgid,
          keys: ['_unsubscribe'],
          sent: new Date(),
          data: {
            keys: keys,
            address: advertise
          }
        };
        message = JSON.stringify(envelope);
        return tasks.push(function(cb) {
          return publisher.publish(msgid, message, address, cb);
        });
      };
      for (i = 0, len = keys.length; i < len; i++) {
        key = keys[i];
        fn(key);
      }
      async.parallel(tasks, function() {
        if (cb != null) {
          return async.delay(cb);
        }
      });
      return unsubscribemsgids;
    },
    hub: hub,
    close: function() {
      publisher.close();
      return receiver.close();
    }
  };
};
