// Generated by CoffeeScript 1.9.2
var async, zmq;

zmq = require('zmq');

async = require('odo-async');

module.exports = function(addresses, onmessage) {
  var addr, fn, i, len, socket, tasks;
  if (!(addresses instanceof Array)) {
    addresses = [addresses];
  }
  socket = zmq.socket('router');
  tasks = [];
  fn = function(addr) {
    return tasks.push(function(cb) {
      return socket.bind(addr, function(err) {
        if (err != null) {
          throw err;
        }
        console.log("ZMQ BIND " + addr);
        return cb();
      });
    });
  };
  for (i = 0, len = addresses.length; i < len; i++) {
    addr = addresses[i];
    fn(addr);
  }
  return async.series(tasks, function() {
    return socket.on('message', function(id, _, msgid, data) {
      return onmessage(data, function() {
        return socket.send([id, '', msgid]);
      });
    });
  });
};
