// Generated by CoffeeScript 1.9.2
module.exports = function() {
  var refs;
  refs = {};
  return {
    ref: function(key, cb) {
      if (refs[key] == null) {
        refs[key] = 1;
        cb();
        return true;
      }
      refs[key]++;
      return false;
    },
    unref: function(key, cb) {
      if (refs[key] == null) {
        console.error(key + " unref'd too much");
        return null;
      }
      refs[key]--;
      if (refs[key] = 0) {
        delete refs[key];
        cb();
        return true;
      }
      return false;
    }
  };
};
