// Generated by CoffeeScript 1.9.2
module.exports = function() {
  var refs;
  refs = {};
  return {
    ref: function(key, cb) {
      if (refs[key] == null) {
        refs[key] = 1;
        return cb();
      }
      return refs[key]++;
    },
    unref: function(key, cb) {
      if (refs[key] == null) {
        return console.error(key + " unref'd too much");
      }
      refs[key]--;
      if (refs[key] === 0) {
        delete refs[key];
        return cb();
      }
    }
  };
};
