// Generated by CoffeeScript 1.9.2
var zmq;

zmq = require('zmq');

module.exports = function(addresses, onreceipt) {
  var socket, startifstopped;
  if (!(addresses instanceof Array)) {
    addresses = [addresses];
  }
  socket = null;
  startifstopped = function() {
    var addr, i, len;
    if (socket != null) {
      return;
    }
    socket = zmq.socket('dealer');
    for (i = 0, len = addresses.length; i < len; i++) {
      addr = addresses[i];
      socket.connect(addr);
      console.log("ZMQ CONNECTED " + addr);
    }
    return socket.on('message', function(_, msgid) {
      msgid = msgid.toString();
      console.log("ZMQ SENT " + msgid);
      return onreceipt(msgid);
    });
  };
  return {
    send: function(msgid, data) {
      startifstopped();
      console.log("ZMQ SENDING " + msgid);
      return socket.send(['', msgid, data]);
    },
    close: function() {
      var addr, i, len, results;
      if (socket == null) {
        return;
      }
      socket.close();
      socket = null;
      results = [];
      for (i = 0, len = addresses.length; i < len; i++) {
        addr = addresses[i];
        results.push(console.log("ZMQ DISCONNECTED " + addr));
      }
      return results;
    }
  };
};
