// Generated by CoffeeScript 1.9.2
var Bus, addresses, bus, publicaddress;

Bus = require('./bus');

addresses = process.argv.slice(2);

publicaddress = addresses[0];

addresses = addresses.slice(1);

bus = Bus(publicaddress, addresses);

setInterval(function() {
  return bus.publish('weather update', 'CLOUDY');
}, 1000);
