// Generated by CoffeeScript 1.9.2
var Bus, bus;

Bus = require('./bus');

bus = Bus({
  bind: process.argv[2],
  datadir: process.argv[3]
});

bus.subscribe('tcp://127.0.0.1:12345', 'weather update');

bus.subscribe('tcp://127.0.0.1:12346', 'weather update');

bus.hub.every('weather update', function(p, cb) {
  console.log(p);
  return cb();
});

setTimeout(function() {
  bus.unsubscribe('tcp://127.0.0.1:12345', 'weather update');
  return bus.unsubscribe('tcp://127.0.0.1:12346', 'weather update');
}, 10000);

process.on('SIGINT', function() {
  bus.close();
  return process.exit(0);
});
