// Generated by CoffeeScript 1.9.2
var Bus, addresses, bus, publicaddress;

Bus = require('./bus');

addresses = process.argv.slice(2);

publicaddress = addresses[0];

addresses = addresses.slice(1);

bus = Bus(publicaddress, addresses);

bus.subscribe('tcp://127.0.0.1:12345', 'weather update');

bus.hub.every('weather update', function(p, cb) {
  console.log(p);
  return cb();
});

setTimeout(function() {
  return bus.unsubscribe('tcp://127.0.0.1:12345', 'weather update');
}, 10000);
