// Generated by CoffeeScript 1.9.2
var cuid, out, publish;

cuid = require('cuid');

publish = require('../publish');

out = publish();

out.connect('one', ['tcp://127.0.0.1:12345']);

out.connect('two', ['tcp://127.0.0.1:12346']);

out.publish(cuid(), 'Hello 1', ['one'], function() {
  return console.log('Hello 1 COMPLETE');
});

out.publish(cuid(), 'Hello 2', ['one', 'two'], function() {
  return console.log('Hello 2 COMPLETE');
});

out.publish(cuid(), 'Hello 3', ['two'], function() {
  return console.log('Hello 3 COMPLETE');
});
