// Generated by CoffeeScript 1.9.2
var Bus, bus, exittimeout, interval, weather;

Bus = require('../bus');

bus = Bus({
  bind: process.argv[2],
  datadir: process.argv[3]
});

weather = ['cloudy', 'sunny', 'overcast', 'meatballs', 'rainy'];

interval = setInterval(function() {
  var i;
  i = Math.floor(Math.random() * weather.length);
  console.log(weather[i]);
  return bus.publish('weather update', weather[i]);
}, 1000);

exittimeout = null;

process.on('SIGINT', function() {
  var close, exit;
  clearInterval(interval);
  close = function() {
    clearTimeout(exittimeout);
    return bus.close();
  };
  exit = function() {
    close();
    console.log('Exiting immediately');
    return process.exit(0);
  };
  if (exittimeout != null) {
    exit();
  }
  exittimeout = setTimeout(exit, 10000);
  console.log('Waiting for queues to empty.');
  console.log('(^C again to quit)');
  return bus.drain(close);
});
