// Generated by CoffeeScript 1.9.2
var Bus, bus, seensigint;

Bus = require('../bus');

bus = Bus({
  bind: process.argv[2],
  datadir: process.argv[3]
});

bus.subscribe('tcp://127.0.0.1:12345', 'weather update');

bus.every('weather update', function(p, cb) {
  console.log(p);
  return cb();
});

seensigint = false;

process.on('SIGINT', function() {
  if (seensigint) {
    console.log('Exiting without confirming unsubscription');
    bus.close();
    process.exit(0);
  }
  seensigint = true;
  console.log('Attempting to unsubscribe');
  return bus.unsubscribe('tcp://127.0.0.1:12345', 'weather update', function() {
    bus.close();
    return process.exit(0);
  });
});
