// Generated by CoffeeScript 1.9.2
var Bus, bus, exittimeout;

Bus = require('../bus');

bus = Bus({
  bind: process.argv[2],
  datadir: process.argv[3]
});

bus.subscribe('tcp://127.0.0.1:12345', 'weather update');

bus.every('weather update', function(p, cb) {
  console.log(p);
  return cb();
});

exittimeout = null;

process.on('SIGINT', function() {
  var close, exit;
  close = function() {
    clearTimeout(exittimeout);
    return bus.close();
  };
  exit = function() {
    close();
    return process.exit(0);
  };
  if (exittimeout != null) {
    exit();
  }
  exittimeout = setTimeout(exit, 10000);
  console.log('Waiting for queues to empty.');
  console.log('(^C again to quit)');
  bus.unsubscribe('tcp://127.0.0.1:12345', 'weather update');
  return bus.drain(close);
});
